body:
  - type: markdown
    attributes:
      value: "## Bug Report"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Email us at thcorporation8@yahoo.com    attributes:
      value: "## Feature Request"
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Email us at thcorporation8@yahoo.com
