name: "Support Request"
description: "Something went wrong and you need help?"

body:
  - type: textarea
    attributes:
      label: "What's wrong?"

bug_report.md:
  name: "Bug Report"
  description: "Report a bug you've encountered."
  body:
    - type: textarea
      attributes:
        label: "Describe the bug"

feature_request.md:
  name: "Feature Request"
  description: "Suggest a new feature or enhancement."
  body:
    - type: textarea
      attributes:
        label: "Describe your feature request"
