templates:
  - name: "Bug Report"
    description: "Report a bug in the project"
    title: "Bug: [Brief description]"
    labels: ["bug"]
    body:
      - type: markdown
        attributes:
          value: "Please provide a clear and concise description of the bug."
      - type: textarea
        id: description
        attributes:
          label: "Description"
          placeholder: "Please describe the bug..."
      - type: textarea
        id: steps_to_reproduce
        attributes:
          label: "Steps to Reproduce"
          placeholder: "1. Step one\n2. Step two\n3. Step three"
      - type: input
        id: environment
        attributes:
          label: "Environment"
          placeholder: "Kodi Version, NerdFeed Version, Operating System, etc."

  - name: "Feature Request"
    description: "Request a new feature for the project"
    title: "Feature Request: [Brief description]"
    labels: ["feature"]
    body:
      - type: markdown
        attributes:
          value: "Please provide a clear and concise description of the feature you would like to see."
      - type: textarea
        id: feature_description
        attributes:
          label: "Feature Description"
          placeholder: "Please describe the feature..."
      - type: textarea
        id: use_case
        attributes:
          label: "Use Case"
          placeholder: "Explain how this feature would be beneficial to users."
